# Site Settings
title: julianbusch.ch
email: jb@quants.ch
baseurl: ""
url: "https://julianbusch.ch"
github_username:  quantsch
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
